diseases_rarity= [
  {"disease": "Common Cold", "rarity": "Common"},
  {"disease": "Flu", "rarity": "Common"},
  {"disease": "Hypertension", "rarity": "Common"},
  {"disease": "Diabetes Type 2", "rarity": "Common"},
  {"disease": "Asthma", "rarity": "Common"},
  {"disease": "Migraine", "rarity": "Common"},
  {"disease": "Gastritis", "rarity": "Common"},
  {"disease": "Anemia", "rarity": "Common"},
  {"disease": "Pneumonia", "rarity": "Common"},
  {"disease": "Chronic Fatigue Syndrome", "rarity": "Uncommon"},
  {"disease": "Osteoarthritis", "rarity": "Common"},
  {"disease": "Eczema", "rarity": "Common"},
  {"disease": "Allergies", "rarity": "Common"},
  {"disease": "Heart Disease", "rarity": "Common"},
  {"disease": "COPD", "rarity": "Common"},
  {"disease": "Thyroid Disorder", "rarity": "Common"},
  {"disease": "Peptic Ulcer", "rarity": "Common"},
  {"disease": "Urinary Tract Infection (UTI)", "rarity": "Common"},
  {"disease": "Gallstones", "rarity": "Common"},
  {"disease": "Irritable Bowel Syndrome (IBS)", "rarity": "Common"},
  {"disease": "Depression", "rarity": "Common"},
  {"disease": "Anxiety", "rarity": "Common"},
  {"disease": "Schizophrenia", "rarity": "Uncommon"},
  {"disease": "Parkinson's Disease", "rarity": "Uncommon"},
  {"disease": "Multiple Sclerosis", "rarity": "Uncommon"},
  {"disease": "Alzheimer's Disease", "rarity": "Uncommon"},
  {"disease": "Tuberculosis", "rarity": "Uncommon"},
  {"disease": "Lung Cancer", "rarity": "Common"},
  {"disease": "Leukemia", "rarity": "Uncommon"},
  {"disease": "HIV/AIDS", "rarity": "Common"},
  {"disease": "Sickle Cell Anemia", "rarity": "Uncommon"},
  {"disease": "Cystic Fibrosis", "rarity": "Uncommon"},
  {"disease": "Hemophilia", "rarity": "Rare"},
  {"disease": "Huntington's Disease", "rarity": "Rare"},
  {"disease": "Kawasaki Disease", "rarity": "Rare"},
  {"disease": "Rheumatoid Arthritis", "rarity": "Uncommon"},
  {"disease": "Fibromyalgia", "rarity": "Uncommon"},
  {"disease": "Meningitis", "rarity": "Uncommon"},
  {"disease": "Tuberculosis", "rarity": "Uncommon"},
  {"disease": "Prostate Cancer", "rarity": "Common"},
  {"disease": "Cervical Cancer", "rarity": "Common"},
  {"disease": "Ovarian Cancer", "rarity": "Uncommon"},
  {"disease": "Endometriosis", "rarity": "Uncommon"},
  {"disease": "Chlamydia", "rarity": "Common"},
  {"disease": "Gonorrhea", "rarity": "Common"},
  {"disease": "Syphilis", "rarity": "Uncommon"},
  {"disease": "Psoriasis", "rarity": "Uncommon"},
  {"disease": "Lupus", "rarity": "Uncommon"},
  {"disease": "Crohn’s Disease", "rarity": "Uncommon"},
  {"disease": "Celiac Disease", "rarity": "Uncommon"},
  {"disease": "Ehlers-Danlos Syndrome", "rarity": "Rare"},
  {"disease": "Marfan Syndrome", "rarity": "Rare"},
  {"disease": "Amyotrophic Lateral Sclerosis (ALS)", "rarity": "Rare"},
  {"disease": "Prion Disease", "rarity": "Rare"},
  {"disease": "Tay-Sachs Disease", "rarity": "Rare"},
  {"disease": "Wilson's Disease", "rarity": "Rare"},
  {"disease": "Cushing's Syndrome", "rarity": "Rare"},
  {"disease": "Addison's Disease", "rarity": "Rare"},
  {"disease": "Achondroplasia", "rarity": "Rare"},
  {"disease": "SARS", "rarity": "Rare"},
  {"disease": "Ebola", "rarity": "Rare"},
  {"disease": "Zika Virus", "rarity": "Rare"},
  {"disease": "Rabies", "rarity": "Rare"},
  {"disease": "Yellow Fever", "rarity": "Rare"},
  {"disease": "Smallpox", "rarity": "Rare"},
  {"disease": "Diphtheria", "rarity": "Rare"},
  {"disease": "Polio", "rarity": "Rare"},
  {"disease": "Typhoid Fever", "rarity": "Rare"},
  {"disease": "Malaria", "rarity": "Uncommon"},
  {"disease": "Hepatitis B", "rarity": "Uncommon"},
  {"disease": "Hepatitis C", "rarity": "Uncommon"},
  {"disease": "Mumps", "rarity": "Rare"},
  {"disease": "Measles", "rarity": "Uncommon"},
  {"disease": "Rubella", "rarity": "Rare"},
  {"disease": "Dengue Fever", "rarity": "Uncommon"},
  {"disease": "Cholera", "rarity": "Rare"},
  {"disease": "Typhus", "rarity": "Rare"},
  {"disease": "Legionnaire's Disease", "rarity": "Rare"},
  {"disease": "Sepsis", "rarity": "Uncommon"},
  {"disease": "Lymphoma", "rarity": "Uncommon"},
  {"disease": "Sarcoidosis", "rarity": "Rare"},
  {"disease": "Cystitis", "rarity": "Common"},
  {"disease": "Psoriatic Arthritis", "rarity": "Uncommon"},
  {"disease": "Bipolar Disorder", "rarity": "Common"},
  {"disease": "Schizoaffective Disorder", "rarity": "Rare"},
  {"disease": "Narcolepsy", "rarity": "Rare"},
  {"disease": "Sleep Apnea", "rarity": "Common"},
  {"disease": "Restless Leg Syndrome", "rarity": "Uncommon"},
  {"disease": "Insomnia", "rarity": "Common"},
  {"disease": "Hemorrhoids", "rarity": "Common"},
  {"disease": "Cystic Acne", "rarity": "Common"},
  {"disease": "Polycystic Ovary Syndrome (PCOS)", "rarity": "Common"},
  {"disease": "Chronic Sinusitis", "rarity": "Common"},
  {"disease": "Bacterial Vaginosis", "rarity": "Common"},
  {"disease": "Panic Disorder", "rarity": "Common"},
  {"disease": "Dystonia", "rarity": "Rare"},
  {"disease": "Myasthenia Gravis", "rarity": "Rare"},
  {"disease": "Graves' Disease", "rarity": "Rare"},
  {"disease": "Autoimmune Hepatitis", "rarity": "Rare"},
  {"disease": "Sjögren’s Syndrome", "rarity": "Rare"}
]
diseases=[]
for e in diseases_rarity:
    diseases.append(e["disease"])
print(diseases)
